# Generated by Django 3.2 on 2022-10-05 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_m3', models.DecimalField(decimal_places=2, help_text='Volume in m3 of the parcel if needed upon Shipping rate', max_digits=9, verbose_name='Volume of the delivered Parcel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Weight in Kilogramms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=24, unique=True, verbose_name='Characteristics designation of a product')),
            ],
        ),
        migrations.CreateModel(
            name='FinitionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('SKU', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Inventory Designation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Public Price')),
                ('period_start', models.DateTimeField(auto_now_add=True, help_text='keep track of the start of a period a price as been attributed.', verbose_name='Sart since')),
                ('period_end', models.DateTimeField(blank=True, help_text='keep track of the end of a period a price as been attributed', null=True, verbose_name='As ended at:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Retail Price')),
                ('period_start', models.DateTimeField(auto_now_add=True, help_text='Duration of given price must be informed for better revenue calcutaion', verbose_name='Start since')),
                ('period_end', models.DateTimeField(auto_now_add=True, help_text='Same as period start for a better revenue calculations', verbose_name='As ended at:')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=24, unique=True, verbose_name='Characteristics designation of a product')),
            ],
        ),
        migrations.CreateModel(
            name='SizeIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(default=0, verbose_name='Units')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('SKU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sku', to='inventory.productdetail')),
            ],
        ),
    ]
