# Generated by Django 3.2 on 2022-10-05 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_ediito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sizeindex',
            name='SKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_sku', to='inventory.productdetail'),
        ),
        migrations.AddField(
            model_name='sizeindex',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='size_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sizeindex',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='size_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sizeindex',
            name='size',
            field=models.ManyToManyField(to='inventory.Size'),
        ),
        migrations.AddField(
            model_name='retailprice',
            name='SKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail_price_sku', to='inventory.productdetail'),
        ),
        migrations.AddField(
            model_name='retailprice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='retail_price_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retailprice',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retail_price_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicprice',
            name='SKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_price_sku', to='inventory.productdetail'),
        ),
        migrations.AddField(
            model_name='publicprice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='public_price_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicprice',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='public_price_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='detail_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detail_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finitionindex',
            name='SKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finition_sku', to='inventory.productdetail'),
        ),
        migrations.AddField(
            model_name='finitionindex',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='finition_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finitionindex',
            name='finition',
            field=models.ManyToManyField(to='inventory.Finition'),
        ),
        migrations.AddField(
            model_name='finitionindex',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='finition_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailweight',
            name='SKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_sku', to='inventory.productdetail'),
        ),
        migrations.AddField(
            model_name='detailweight',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='weight_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailweight',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weight_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailvolume',
            name='SKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_sku', to='inventory.productdetail'),
        ),
        migrations.AddField(
            model_name='detailvolume',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='volume_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailvolume',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='volume_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
