# Generated by Django 3.2 on 2022-11-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicprice',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='publicprice',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='retailprice',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='retailprice',
            name='period_start',
        ),
    ]
